version: '3'

services:

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: 'sample-metrics-bot-worker'
    restart: always
    volumes:
      - .:/app/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - tier

networks:
  tier:
    external:
      name: telegram-bots-network