apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: MySQL test_db
    type: mysql
    access: proxy
    url: mysql:3306
    database: test_db
    user: root
    secureJsonData:
      password: password
    isDefault: false